#!/bin/sh

set -e

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/prerm.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/prerm.mysql
  dbc_go zabbix-quanta-mysql $@
fi

#DEBHELPER#
