#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  dbc_generate_include_args="-o template_infile=/usr/share/dbconfig-common/data/zabbix-quanta-mysql/install/mysql/quanta_mysql"
  dbc_generate_include_owner='root:zabbix'
  dbc_generate_include_perms=640
  dbc_generate_include=template:/var/lib/zabbix/quanta/etc/quanta_mysql
  dbc_go zabbix-quanta-mysql $@
fi

if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d zabbix-agent restart
else
  /etc/init.d/zabbix-agent restart
fi

db_stop
#DEBHELPER#

exit 0
